spring:
  config:
    activate:
      on-profile: release

kafka:
  bootstrap-servers: 10.161.135.47:9093,10.161.135.48:9093,10.161.135.49:9093
  group-id: library_kafka_resolver
  max-fetch-size: 786432

---

spring:
  config:
    activate:
      on-profile: local

kafka:
  bootstrap-servers: 10.161.135.47,10.161.135.48,10.161.135.49
  group-id: library_test
  max-fetch-size: 3145728
